-- 環境のセットアップ
USE SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES;
USE WAREHOUSE SUPPLY_CHAIN_ASSISTANT_WH;
USE ROLE SUPPLY_CHAIN_ASSISTANT_ROLE;

-- PDF 解析のためにウェアハウスをスケールアップ（計算集約型の処理）
ALTER WAREHOUSE SUPPLY_CHAIN_ASSISTANT_WH SET WAREHOUSE_SIZE = 'X-LARGE';

-- Cortex PARSE_DOCUMENT を使用してステージ内のすべての PDF を解析
-- 各 PDF からレイアウト情報付きでテキストコンテンツを抽出
CREATE OR REPLACE TABLE PARSE_PDFS AS 
SELECT RELATIVE_PATH, SNOWFLAKE.CORTEX.PARSE_DOCUMENT(@SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.SUPPLY_CHAIN_ASSISTANT_PDF_STAGE,RELATIVE_PATH,{'mode':'LAYOUT'}) AS DATA
    FROM DIRECTORY(@SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.SUPPLY_CHAIN_ASSISTANT_PDF_STAGE);

-- 解析した PDF コンテンツを検索可能なセグメントにチャンク分割
-- コンテキストの連続性を保つため、1800文字のチャンクに300文字のオーバーラップで分割
-- ソース PDF へのクリック可能なリンク用に事前署名付き URL を生成（7日間有効）
CREATE OR REPLACE TABLE PARSED_PDFS AS (
    WITH TMP_PARSED AS (SELECT
        RELATIVE_PATH,
        SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(TO_VARIANT(DATA):content, 'MARKDOWN', 1800, 300) AS CHUNKS
    FROM PARSE_PDFS WHERE TO_VARIANT(DATA):content IS NOT NULL)
    SELECT
        TO_VARCHAR(C.value) AS PAGE_CONTENT,                              -- 検索可能なテキストコンテンツ
        REGEXP_REPLACE(RELATIVE_PATH, '\\.pdf$', '') AS TITLE,             -- ドキュメントタイトル（.pdf なしのファイル名）
        'SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.SUPPLY_CHAIN_ASSISTANT_PDF_STAGE' AS INPUT_STAGE,
        RELATIVE_PATH AS RELATIVE_PATH,                                    -- 元のファイルパス
        GET_PRESIGNED_URL(@SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.SUPPLY_CHAIN_ASSISTANT_PDF_STAGE, RELATIVE_PATH, 604800) AS PRESIGNED_URL  -- クリック可能な URL（7日後に期限切れ）
    FROM TMP_PARSED P, LATERAL FLATTEN(INPUT => P.CHUNKS) C
);

-- 重い処理が完了した後、ウェアハウスをスケールダウン
ALTER WAREHOUSE SUPPLY_CHAIN_ASSISTANT_WH SET WAREHOUSE_SIZE = 'SMALL';

-- PDF コンテンツに対するセマンティック検索用の Cortex Search サービスを作成
-- PAGE_URL は Snowflake Intelligence でのクリック可能なソースリンク用の事前署名付き URL にマッピング
CREATE OR REPLACE CORTEX SEARCH SERVICE SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.SUPPLY_CHAIN_INFO
ON PAGE_CONTENT                                      -- プライマリ検索フィールド
WAREHOUSE = SUPPLY_CHAIN_ASSISTANT_WH
TARGET_LAG = '1 hour'                                -- 新しいドキュメントの更新間隔
AS (
    SELECT PRESIGNED_URL AS PAGE_URL, PAGE_CONTENT, TITLE, RELATIVE_PATH
    FROM PARSED_PDFS
);

-- 事前署名付き URL が期限切れになる前に更新するスケジュールタスクを作成
-- 事前署名付き URL は7日後に期限切れになるため、リンクの有効性を確保するために毎日更新
CREATE OR REPLACE TASK SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.REFRESH_PRESIGNED_URLS_TASK
  WAREHOUSE = SUPPLY_CHAIN_ASSISTANT_WH
  SCHEDULE = 'USING CRON 0 1 * * * America/Los_Angeles'  -- 毎日 PST 午前1時に実行
AS
UPDATE SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.PARSED_PDFS
SET PRESIGNED_URL = GET_PRESIGNED_URL(@SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.SUPPLY_CHAIN_ASSISTANT_PDF_STAGE, RELATIVE_PATH, 604800);

-- タスクを有効化して自動 URL 更新を開始
ALTER TASK SUPPLY_CHAIN_ASSISTANT_DB.ENTITIES.REFRESH_PRESIGNED_URLS_TASK RESUME;
